### ISSUE TITLE
Demonstrate single-sensor fault tolerance - 3HR

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#10]
We want to demonstrate the fault tolerance module detecting faults and also reporting them, and, in some cases, changing the state to a critical fault state.  

Single-sensor faults can be demonstrate by unplugging an I2C digitally connected component, such as a power supply.

**Comment by ForrestErickson** [comment]
@RobertLRead ,
Status?
Can this be closed or marked Will Not Fix?
