### ISSUE TITLE
add wiring connector for ease of assembly for power supply

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#108]
Connector for adding a wire interface to power supply
PHDR-24VS
CONN RCPT HSG 24POS 2.00MM

Jumper wires for building up the connector,
APAPA22K305
JUMPER SPHD-001T-P0.5 X2 12"

crimps for making custom wires
SPHD-002T-P0.5
CONN SOCKET 24-28AWG CRIMP TIN

Crimper that "should" work with SPHD-002T-P0.5
https://www.amazon.com/gp/product/B078WPT5M1/

Mating connectors, to be placed on eventual control board or wiring board. 
B24B-PHDSS(LF)(SN)         Description: CONN HEADER VERT 24POS 2MM
S24B-PHDSS(LF)(SN)         Description:  CONN HEADER R/A 24POS 2MM

Manual for power supply with pinout, https://www.xppower.com/portals/0/pdfs/SF_HDS800.pdf

**Comment by ForrestErickson** [comment]
The Controller V1 has implemented the B24B-PHDSS(LF)(SN) connector.

Closing since the PCB design was released and ordered on about 20230828.
If there are problems found with the Controller V1, issues should be created at that time.
