### ISSUE TITLE
HAL code for heater refers to the GGLABS SSR but we are no longer using that...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#109]
We now use an SSR from Adafruit. The code in place functions, but is confusing because it refers to the wrong hardware.

**Comment by ForrestErickson** [comment]
@RobertLRead 
Please identify the project status (No Status, Backlog, In Progress....)
Please identify a target milestone for completion.

Might identify which source code files have the incorrect reference.

**Comment by RobertLRead** [comment]
Closed as done
