### ISSUE TITLE
change mech/frontpanel/Labels Rev1_3.svg 

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#112]
the label Stack 1 Stack 2 and Stack three should be relabled Stack 1 & 2, Stack 3 & 4, Stack 5 & 6

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
Please document the Serial number 2 unit status.

**Comment by LokiMetaSmith** [comment]
Since OEDCS#1 &2 were built for single stack configurations, this point is moot.
