### ISSUE TITLE
Design control board interconnect pcb

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#120]
This board should incorporate features from the existing odecos configuration, and add features nessisary to connect to the plant panel

**Comment by LokiMetaSmith** [comment]
Initial board schematic has been created and uploaded to the repo

ToDo
- [ ] Wire up the power supply labels to the Due
- [x] Add hookups for thermocouples
- [x] implement proper fan control circuit
- [x] add SSR control lines and connector
- [x] add mounting hardware points
- [x] add DB9 and DB25 
- [ ]

**Comment by ForrestErickson** [comment]
Lots of progress on 23 and 24th of August.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/b59b892b-be48-4f83-a2b9-1121fa30ef9b)

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
@RobertLRead ,

Regarding, " Wire up the power supply labels to the Due"
Is this the +12 that is simply wired into the Due?  Am I to infer that the Due has an onboard regulator that can dissipate the heat that will result from a +12 input power?

I am left wondering, **What is the current on Unit1 at the Due input?**

**Comment by ForrestErickson** [comment]
This task is done with the release and order of PWA from JLCPCB on about 20230828
![image](https://github.com/PubInv/NASA-COG/assets/5836181/e6c101fa-5d97-4cef-b6b8-287229e86936)

**Comment by ForrestErickson** [comment]
Closing since the PCB design was released and ordered on about 20230828.
If there are problems found with the Controller V1,  issues should be created at that time.
