### ISSUE TITLE
During ramp down, Digital power supply mysteriously started outputting zero volts...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#142]
I don't know what caused this. Possibly this was an amperage limitation and when the temperature dropped to 450C the resitance became so high that the intelligent power supply decided to shut off the supply. This is bad because we are supposed to maintain a 1.0 V bias at all times. Possibly our overall algorithm should be: Limit to X watts, but when below Y watts, apply 1.0 Volts.

**Comment by LokiMetaSmith** [comment]
you can maintain a higher voltage than 1v, it's just they wanted a bias voltage maintained.
