### ISSUE TITLE
Make Schematic Symbol and PCB Footprint, MAX31855, SPI Interface

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/NASA-COG#151]
Reference material: 
* https://learn.adafruit.com/connecting-the-max31855-thermocouple-amplifier-breakout-to-an-electric-imp
* https://www.adafruit.com/product/269

![image](https://github.com/PubInv/NASA-COG/assets/5836181/dd808018-c650-4b38-b508-7c08db4d950c)

![image](https://github.com/PubInv/NASA-COG/assets/5836181/5aae22fc-741e-4e22-9ae7-3910d31a7936)

**Comment by ForrestErickson** [comment]
@LokiMetaSmith
Please measure to see of the mounting holes on the MAX31850 are connected to the circuit ground.

**Comment by ForrestErickson** [comment]
![image](https://github.com/PubInv/NASA-COG/assets/5836181/27ae8f94-cb98-4580-9860-07c4f7122908)

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
Please test fit all three types on this PDF.
[MAX31850_PCB20230824_0752.pdf](https://github.com/PubInv/NASA-COG/files/12429093/MAX31850_PCB20230824_0752.pdf)

Please leave feedback, photos, on the fit of the MAX31855 on this issue PubInv/NASA-COG#151

**Comment by LokiMetaSmith** [comment]
PubInv/NASA-MCOG#51 is related to this issue, and can be closed when the PCB files are changed

**Comment by ForrestErickson** [comment]
Done with V1.1
