### ISSUE TITLE
Change D4 to D5 for the Dallas One Wire interface to Thermocouples because D4 is the SD card enable on the Ethernet shield

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#167]

**Comment by RobertLRead** [comment]
I began this work. None of the pins except D4 work out of the box. D5 works if I had a 4.6 kOhm pull-up resistor to the data line. This implies that we should rework the perfboard holding the SN-1 OEDCS, and possibly add an additional external pull-up resistor to the control board that @ForrestErickson is currently designing. I spoke to Lee and there is already a 4.7kOhm resistor on D5 in the controller board being designed, so that should be all that is required. However, i will leave this open until we can discuss it further.

**Comment by ForrestErickson** [comment]
Done on the V1 Controller board.

D5
![image](https://github.com/PubInv/NASA-COG/assets/5836181/37824d7e-fb82-4701-b57c-f47e7e239e0f)

Pull up resistor
![image](https://github.com/PubInv/NASA-COG/assets/5836181/5045b3f7-860d-46ec-9ddb-3bed65af562a)

Closing as done.

CC:
@LokiMetaSmith 
@RobertLRead
