### ISSUE TITLE
measurements must not be enclosed in quotes

### ISSUE THREAD

**Issue by gmulligan** [PubInv/NASA-COG#178]
The json value sent for StackOhms is "-1.0"...  It should be just -1.0

Numbers should not be enclosed in quotes unless it is supposed to be a string literal.

Cumulocity will not accept string literals for measurments.

**Comment by RobertLRead** [comment]
I have fixed this. I have also changed the MachineState to be reported as a number. Here is the 8 state names:

```
  constexpr inline static char const *MachineStateNames[8] = {
    "Off",
    "Warmup",
    "NormalOperation",
    "Cooldown",
    "CriticalFault",
    "EmergencyShutdown",
    "OffUserAck"
  };
```
