### ISSUE TITLE
Confirm on Controller V1 Assemblies that Fan Does Not Go Full Blast on Reset, Power On

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/NASA-COG#186]
Refer to issue #95 
@LokiMetaSmith 
@RobertLRead 

Done but this should be tested when Controller V1 assemblies are integrated into Serial Number 1 and Serial Number 2.

I will close this task because the circuit design has been done. 
A new task for Robert will be confirming, testing the functionality of Controller V1 printed wiring assembly.

**Comment by LokiMetaSmith** [comment]
This needed firmware changes to set the initial GPIO state off (or on in case of Control v1) and works as intended now
