### ISSUE TITLE
errors running "pio test -e due_ribbonfish -f "test_stage2_heater" -vvv"

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#187]
Installed CLI version of platform.io, running "pio upgrade"  shows it correctly installed. 

Below is the output of "pio test -e due_ribbonfish -f "test_stage2_heater" -vvv"

Collected 5 tests (test_SanyoAceB97, test_debug, test_heater_ramp, test_parse_script, test_stage2_heater)

Processing test_stage2_heater in due_ribbonfish environment
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Building & Uploading...
CONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/due.html
PLATFORM: Atmel SAM (8.2.0) > Arduino Due (Programming Port)
HARDWARE: AT91SAM3X8E 84MHz, 96KB RAM, 512KB Flash
DEBUG: Current (atmel-ice) External (atmel-ice, blackmagic, jlink, stlink)
PACKAGES:
 - framework-arduino-sam @ 1.6.12
 - framework-cmsis @ 1.40500.0 (4.5.0)
 - framework-cmsis-atmel @ 1.2.2
 - tool-bossac @ 1.10700.190624 (1.7.0)
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Found 20 compatible libraries
Scanning dependencies...
Warning! Circular dependencies detected between `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\task` and `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\core`
Warning! Circular dependencies detected between `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\hal` and `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\task`
Warning! Circular dependencies detected between `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\hal` and `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\core`
Warning! Circular dependencies detected between `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\task` and `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\.pio\libdeps\due_ribbonfish\Ethernet`
Warning! Circular dependencies detected between `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\task` and `C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware\lib\networking_task`

Building in test mode
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libbf6\task\retrieve_script_UDP_task.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\task\retrieve_script_UDP_task.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libbf6\task\stage2_heater_task.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\task\stage2_heater_task.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\config.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pIn file included from lib\networking_task/Server.h:32:0,
io\libdeps\du                 from .pio\libdeps\due_ribbonfish\Ethernet\src/Ethernet.h:53,
e_ribbonfish\PIRDS -I.pio\libde                 from lib\task\retrieve_script_UDP_task.cpp:35:
ps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\lib\networking_task/mongoose.h:42:2: error: #error "MG_ARCH is not specified and we couldn't guess it."
task #error "MG_ARCH is not specified and we couldn't guess it."
   ^~~~-I.pi~
o\lib\networking_task/mongoose.h:59:10: fatal error: mongoose_custom.h: No such file or directory
li
*************************************************************************
* Looking for bdmongoose_custom.hep dependency? Check our library registry!
*
* CLI  > platformio lib search "header:mongoose_custom.h"
* Web  > s\https://registry.platformio.org/search?q=header:mongoose_custom.hdu
*
*************************************************************************

e_ #include <mongoose_custom.h>
r          ^~~~i~b~b~o~n~f~i~s~h~\~S~F~M~3~X~0
0compilation terminated.
 "*** [.pio\build\due_ribbonfish\libbf6\task\retrieve_script_UDP_task.cpp.o] Error 1
-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variIn file included from lib\core\include/task.h:29:0,
ant                 from lib\core\include/scheduler.h:29,
s\a                 from lib\core\include/core.h:29,
rdu                 from lib\task/state_machine_manager.h:25,
ino                 from lib\task\stage2_heater_task.h:25,
_du                 from lib\task\stage2_heater_task.cpp:16:
e_xlib\task/machine.h:175:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
 li   constexpr inline static char const *MachineStateNames[8] = {
b\                                       ^~~~c~o~r~e~\~s~rc~~~\~c~o~n~fig
.clib\task/machine.h:184:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
pp
   constexpr inline static char const *MachineSubStateNames[2] = {
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\core.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=840000                                       ^~~~0~0~L~ ~-~D~U~S~B~C~O~~~~N~ ~-
DUlib\task/machine.h:188:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
SB_   constexpr inline static char const *TempLocationNames[2] = {
VI                                       ^~~~D~=~0~x~2~3~4~1~ ~-~D~U~S~B
_Plib\task\stage2_heater_task.cpp: In member function 'virtual bool OxApp::Stage2HeaterTask::_run()':
ID=lib\task\stage2_heater_task.cpp:50:5: warning: no return statement in function returning non-void [-Wreturn-type]
0x0     }
03E     ^
 "-lib\task\stage2_heater_task.cpp: In member function 'virtual MachineState OxApp::Stage2HeaterTask::_updatePowerComponentsCooldown()':
DUSlib\task\stage2_heater_task.cpp:117:5: error: expected unqualified-id before 'return'
B_P     return new_ms;
RO     ^~~~D~U~C
T=lib\task\stage2_heater_task.cpp: In member function 'virtual MachineState OxApp::Stage2HeaterTask::_updatePowerComponentsOperation(IdleOrOperateSubState)':
\"Alib\task\stage2_heater_task.cpp:142:11: warning: unused variable 't' [-Wunused-variable]
rdu     float t = getConfig()->report->post_heater_C;
ino            ^
Duelib\task\stage2_heater_task.cpp: In member function 'virtual MachineState OxApp::Stage2HeaterTask::_updatePowerComponentsCooldown()':
\""lib\task\stage2_heater_task.cpp:118:3: warning: control reaches end of non-void function [-Wreturn-type]
 -D   }
USB   ^
_MA*** [.pio\build\due_ribbonfish\libbf6\task\stage2_heater_task.cpp.o] Error 1
NUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformioIn file included from lib\core\include/task.h:29:0,
\pa                 from lib\core\include/scheduler.h:29,
c                 from lib\core\include/core.h:29,
kag                 from lib\core\src\core.cpp:18:
es\lib\task/machine.h:175:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
fra   constexpr inline static char const *MachineStateNames[8] = {
me                                       ^~~~w~o~r~k~-~a~r~d~u~i~n~o~-~s
amlib\task/machine.h:184:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
\li   constexpr inline static char const *MachineSubStateNames[2] = {
br                                       ^~~~a~r~i~e~s~\~S~P~I~\~s~r~c~ ~-~I~l
iblib\task/machine.h:188:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
\co   constexpr inline static char const *TempLocationNames[2] = {
ll                                       ^~~~e~c~t~i~o~n~s~ ~-~I~C~:~\~U
selib\core\src\core.cpp: In member function 'void OxCore::Core::Tick()':
rs\lib\core\src\core.cpp:121:15: warning: unused variable 'state' [-Wunused-variable]
Lok     TaskState state = _scheduler.RunNextTask(elapsed);
i-V               ^~~~R~\
.platforIn file included from lib\core\include/task.h:29:0,
mio                 from lib\core\include/scheduler.h:29,
\pa                 from lib\core\include/core.h:29,
cka                 from lib\core\src\error_handler.cpp:25:
geslib\task/machine.h:175:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
\fr   constexpr inline static char const *MachineStateNames[8] = {
am                                       ^~~~e~w~o~r~~~~k~-~a~r~d~u~i
nolib\task/machine.h:184:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
-sa   constexpr inline static char const *MachineSubStateNames[2] = {
m\                                       ^~~~c~o~r~e~s~\~a~r~d~u~i~n~o~ ~-~I~C
:\Ulib\task/machine.h:188:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
ser   constexpr inline static char const *TempLocationNames[2] = {
s\Loki-VR\.platfor                                       ^~~~mio\packages\framewo~r~k~-~a~r~d~u~i~n~o~-~s~a
m\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\core\src\core.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\debug.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\core\src\debug.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\error_handler.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\core\src\error_handler.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\logger.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\core\src\logger.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\scheduler.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\LoIn file included from lib\core\include/task.h:29:0,
ki-                 from lib\core\include/scheduler.h:29,
VR\                 from lib\core\src\scheduler.cpp:27:
.pllib\task/machine.h:175:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
atf   constexpr inline static char const *MachineStateNames[8] = {
or                                       ^~~~m~i~o~\~p~a~c~k~a~g~e~s~\~f
ralib\task/machine.h:184:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
mew   constexpr inline static char const *MachineSubStateNames[2] = {
or                                       ^~~~k~-~a~r~d~u~i~n~o~-~s~a~m~\~s~y~s
telib\task/machine.h:188:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
m\C   constexpr inline static char const *TempLocationNames[2] = {
MS                                       ^~~~I~S~\~D~e~v~i~c~e~\~A~T~M~E
LIn file included from lib\core\include/task.h:29:0,
 -I                 from lib\core\src\task.cpp:25:
C:lib\task/machine.h:175:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
\Us   constexpr inline static char const *MachineStateNames[8] = {
e                                       ^~~~r~s~\~L~o~k~i~-~V~R~\~.~p~l
atlib\task/machine.h:184:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
for   constexpr inline static char const *MachineSubStateNames[2] = {
mi                                       ^~~~o~\~p~a~c~k~a~g~e~s~\~f~r~a~m~e~
wolib\task/machine.h:188:39: warning: inline variables are only available with -std=c++1z or -std=gnu++1z
rk-   constexpr inline static char const *TempLocationNames[2] = {
ar                                       ^~~~d~u~i~n~o~-~s~a~m~\~v~a~r~i
ants\arduino_due_x lib\core\src\scheduler.cpp
arm-none-eabi-g++ -o .pio\build\due_ribbonfish\libcc2\core\task.cpp.o -c -fno-rtti -fno-exceptions -std=gnu++11 -fno-threadsafe-statics -mcpu=cortex-m3 -mthumb -Os -ffunction-sections -fdata-sections -Wall -nostdlib --param max-inline-insns-single=500 -DPLATFORMIO=60111 -D__SAM3X8E__ -DARDUINO_SAM_DUE -DBUILD_ENV_NAME=due_ribbonfish -DRIBBONFISH=1 -DUSE_MAX31850_THERMOCOUPLES=1 -DARDUINO=10805 -DF_CPU=84000000L -DUSBCON -DUSB_VID=0x2341 -DUSB_PID=0x003E "-DUSB_PRODUCT=\"Arduino Due\"" -DUSB_MANUFACTURER=\"Arduino\" -DARDUINO_ARCH_SAM -DPIO_UNIT_TESTING -Ilib\networking_task -I.pio\libdeps\due_ribbonfish\PIRDS -I.pio\libdeps\due_ribbonfish\Ethernet\src -I.pio\libdeps\due_ribbonfish\PIRCS -I.pio\libdeps\due_ribbonfish\PID -Ilib\hal -Ilib\core\include -Ilib\core\src -Ilib\task -I.pio\libdeps\due_ribbonfish\SFM3X00 "-I.pio\libdeps\due_ribbonfish\Adafruit DS3502" "-I.pio\libdeps\due_ribbonfish\Adafruit BusIO" -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\Wire\src -I.pio\libdeps\due_ribbonfish\DallasTemperature -I.pio\libdeps\due_ribbonfish\OneWire -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\libraries\SPI\src -Ilib\collections -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\cores\arduino -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\libsam -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\CMSIS\Include -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\system\CMSIS\Device\ATMEL -IC:\Users\Loki-VR\.platformio\packages\framework-arduino-sam\variants\arduino_due_x lib\core\src\task.cpp
Uploading stage has failed, see errors above. Use `pio test -vvv` option to enable verbose output.
------------------------------------------------------------------------------------------------------------------------------------------------------ due_ribbonfish:test_stage2_heater [ERRORED] Took 5.94 seconds ------------------------------------------------------------------------------------------------------------------------------------------------------

================================================================================================================================================================================= SUMMARY =================================================================================================================================================================================
Environment     Test                Status    Duration
--------------  ------------------  --------  ------------
due_ribbonfish  test_debug          SKIPPED
due_ribbonfish  test_heater_ramp    SKIPPED
due_ribbonfish  test_parse_script   SKIPPED
due_ribbonfish  test_SanyoAceB97    SKIPPED
due_ribbonfish  test_stage2_heater  ERRORED   00:00:05.938
================================================================================================================================================================ 1 test cases: 0 succeeded in 00:00:05.938 ================================================================================================================================================================
PS C:\Users\Loki-VR\Documents\projects\NASA-COG\firmware>

**Comment by RobertLRead** [comment]
I've moved networking_task out of the firmware directorty; it was reference code. It make work now. @LokiMetaSmith
