### ISSUE TITLE
SPI interface differences between Uno and Due

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#218]
Notice that on the Uno have pins 11,12,13 tied to the ICSP programming header and in the Due 11,12,13 **are not associated with SPI**

This took some digging, but the Ethernet shield uses the ICSP header, and not pins 11,12,13 (they aren't even connected) 
which matches with why the ethernet shield, "just works". Also Pins 4, 10, 52 are unique 

The repercussions of this are subtitle. For one, neither of the din rail break out boards also bring out SPI pins from the ICSP, using the display isn't  possible without another break out cable, and the same goes for SPI based thermocouples and ethernet boards. 

On the plus side, the SPI was correctly brought out on the control board, so SPI based thermcouples will work with that board. 

Uno
![image](https://github.com/PubInv/NASA-COG/assets/5054116/4f5320b9-69e2-4027-b50e-3ea61296d8ce)

DUE
![image](https://github.com/PubInv/NASA-COG/assets/5054116/804b629a-cb67-421b-9de1-f856b2519d18)

here's a better reference for 
![image](https://github.com/PubInv/NASA-COG/assets/5054116/0cbeaa6c-bb05-4a79-8334-1f7ebb1f4f2b)

source: https://forum.arduino.cc/t/due-pinout-diagram/129258

and the full pinout
https://content.arduino.cc/assets/A000056-full-pinout.pdf

**Comment by RobertLRead** [comment]
"using the display isn't "   - what? your comment seems garbled.

Nonetheless this is great research.

**Comment by LokiMetaSmith** [comment]
I've corrected the post above. 

Additional information. A work around is to use software SPI, with the cavate that the bit rate will be slower, but for this application that maybe more than acceptable.

**Comment by ForrestErickson** [comment]
Regarding, 
"This took some digging, but the Ethernet shield uses the ICSP header, and not pins 11,12,13 (they aren't even connected)
which matches with why the ethernet shield, "just works". Also Pins 4, 10, 52 are unique"

Regarding "pins 11,12,13 " do you mean on your Ethernet shield?  The Due?

To which exact make and model Ethernet  shield are you referring?

I have ordered, but not yet received, seeed studio Ethernet Shield.
https://www.amazon.com/dp/B00W0HZVMS?psc=1&ref=ppx_yo2ov_dt_b_product_details
Mine is Arriving September 15 - September 26.

**Comment by ForrestErickson** [comment]
Regarding SPI to thermocouples, 
For reference, here is the PCB routing
![image](https://github.com/PubInv/NASA-COG/assets/5836181/dcb898be-dfec-46a0-b53e-e57450b19830)

With a flying wire you could connect the SPI clock from the test point to the header pin to get SPI to the D13 if that helps.  The KiCad "measurement tool" on this screen shot evokes such a connection.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/b57c4b67-9638-4385-9b5c-0b744b3312bb)

**Comment by ForrestErickson** [comment]
Similar for MISO to D12.      Make D12 high impedance (INPUT) to prevent contention.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/ce1e6498-7b95-4256-a4d5-c574acf840fc)

**Comment by ForrestErickson** [comment]
Wire MOSI and pin D11.   Make D11 high impedance (INPUT) to prevent contention.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/f514d5b7-8b34-4360-92a3-78df6c94a467)

**Comment by ForrestErickson** [comment]
Is it right to assume the nCS could be D10 for the Ethernet?
![image](https://github.com/PubInv/NASA-COG/assets/5836181/b5c350ee-5c42-4b01-9709-e91e44d64130)

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
Regarding the issue name, "SPI interface differences between Uno and Due"
Does this make a problem, with for example the Ethernet shield? And if so please describe the problem. Edit the original details may help, may be the best place to do so.

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
Regarding, " A work around is to use software SPI,"  

Do you mean " A work around is to use software SPI, for the Ethernet card"?

**Comment by LokiMetaSmith** [comment]
> Regarding, "This took some digging, but the Ethernet shield uses the ICSP header, and not pins 11,12,13 (they aren't even connected) which matches with why the ethernet shield, "just works". Also Pins 4, 10, 52 are unique"
> 
> Regarding "pins 11,12,13 " do you mean on your Ethernet shield? The Due?
> 
> To which exact make and model Ethernet shield are you referring?
> 
> I have ordered, but not yet received, seeed studio Ethernet Shield. https://www.amazon.com/dp/B00W0HZVMS?psc=1&ref=ppx_yo2ov_dt_b_product_details Mine is Arriving September 15 - September 26.

The Ethernet shield v2 from Seeed Studio also do not use pin 11,12,13
![image](https://github.com/PubInv/NASA-COG/assets/5054116/d7e744ec-90c8-4deb-b91e-9ee867b7dca3)

**Comment by LokiMetaSmith** [comment]
> @LokiMetaSmith Regarding, " A work around is to use software SPI,"
> 
> Do you mean " A work around is to use software SPI, for the Ethernet card"?

A work around to not having access to the ICSP header is to use software SPI. This is presently only the case on the Stage 2 heater controller

**Comment by LokiMetaSmith** [comment]
> @LokiMetaSmith
> Regarding the issue name, "SPI interface differences between Uno and Due"
> Does this make a problem, with for example the Ethernet shield? And if so please describe the problem. Edit the original details may help, may be the best place to do so.

This can cause confusion and misunderstanding, as a quick search for "Due and SPI" will attest. In my own case, the poor documentation around it, caused quite a bit of confusion because the ethernet shield does use SPI, but it's not clear where those pins are defined, and the naive assumption is that the Due is pin to pin compatible with the Uno, which is only partly true

**Comment by LokiMetaSmith** [comment]
![PXL_20230909_175124601](https://github.com/PubInv/NASA-COG/assets/5054116/a9d499c1-12c7-478d-a31b-b48bcea575aa)
This was fixed in the stage 2 heater with a ribbon cable and direct wire of d4 to d4 and d10 to d10

**Comment by RobertLRead** [comment]
@LokiMetaSmith is this now closable? If so, please close it.

**Comment by LokiMetaSmith** [comment]
closing issue
