### ISSUE TITLE
Have Idle Task Toggle a Pin.

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/NASA-COG#228]
Allows to monitor the task loading with an oscilloscope.

**Comment by ForrestErickson** [comment]
Lee would like to be coached to do this.

**Comment by RobertLRead** [comment]
This is assigend to @ForrestErickson as a  learning exercise to be supported by @LokiMetaSmith (Rob is out of office.)

**Comment by RobertLRead** [comment]
Note: This can first me made as a task.
It could later be improved by going into the Core and toggle a pin at the completion of each task.

**Comment by ForrestErickson** [comment]
We decided to create a task called heartbeat with the files: heartbeat_task.h and heartbeat_task.cpp
We will copy and rename fault_task.h and fault_task.cpp as our donor.

**Comment by ForrestErickson** [comment]
We have success. Here is the heartbeat toggeling the LED_BUILTIN at the fastest rate it can.

![image](https://github.com/PubInv/NASA-COG/assets/5836181/d5eabd99-6a99-499c-81e7-a0252a96a042)

**Comment by RobertLRead** [comment]
Great work.

**Comment by ForrestErickson** [comment]
Working code pushed.
