### ISSUE TITLE
The DeltaFans can't use PWM for main power supply....

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#27]
therefore wiring can be simplified by tying the power directly the 12V rail---this will also simplify the software.

**Comment by ForrestErickson** [comment]
@RobertLRead ,
Status?
Can this be closed or marked Will Not Fix?

I assume this is moot since Controller V1 assemblies work with the blower.

**Comment by RobertLRead** [comment]
Closed as moot.
