### ISSUE TITLE
Stage2 Thermocouple Bad Readings With Extension Cables

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#310]
This is to record issues reported on Oct. 2nd/3rd by AmOx based that were found when extension cables were added to the thermocouples for the Stage2 (Pathfinder) sensing.

**Comment by ForrestErickson** [comment]
How can Lee see reports of these "bad readings"?
Photographs or other descriptions of "Extension Cables" so we can reproduce the setup?

The description says Stage 2 so assuming this is this the system Lawrence built for the high pressure. Am I correct?

**Comment by RobertLRead** [comment]
This is probably no longer operable.
