### ISSUE TITLE
Detect Loss of Service Power, Hardware Component, Control V1.1 PCB

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#330]
This could be in a number of different ways.

Let us assume that, as we currently have, a battery backup for the Due. Then the Due will run while we have loss of AC "mains" power.

At present, this will cause loss to the digital power supply, which will show up (I think) as return values.

However, the digital power supply could in fact fail separately, therefore, it would be nice to tell if the AC power had failed directly. There is probably an electronic component (such as a Hall effect sensor) that would do this. I'm sure it could be done with a diode and a high-ohmage resistor as well; I will leave that to others to decide if that is a good idea or not. 

PROBABLY this should be detected in the CogTask "_run" routine like all the other ones.

**Comment by ForrestErickson** [comment]
The TF800 programable switching power supply has an AUX output on what appears to be three pins which can be 5V or 9V. 

### Detect Loss of Service Power
If power to the TF800 is lost we could detect this because AUX would go low. 

Resistor divider 14.7/24.7 * 5 = 2.98V. So use 10K into 4K7+10K.

**Comment by ForrestErickson** [comment]
20231011 Lee added resistors to sense the AUX power from Supply 1 and Supply 2 to schematic and PCB.

![image](https://github.com/PubInv/NASA-COG/assets/5836181/a8d8abf9-b7cc-42f8-a2a7-20a4905854be)
![image](https://github.com/PubInv/NASA-COG/assets/5836181/ec123c71-9dc9-4998-84af-8df24b7f54fa)

![image](https://github.com/PubInv/NASA-COG/assets/5836181/4bece3ce-a53c-4d7c-8b4c-50b5331fc6db)

This should give a hardware component to the solution.

Still required will be firmware to pole A3 and A4 for which Lee will make a separate issue.
