### ISSUE TITLE
JLCPCB, Gerbers, BOM and Placement From KiCad Issues, Control V1.1

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#342]
![image](https://github.com/PubInv/NASA-COG/assets/5054116/e7923a8c-766b-4aaf-b90a-daf69f1ae959)

in Control_1V1_SFTtoBOM.xls

jlcpcb doesn't like like designators like C1-C15, needs to be C1, C2, C3, C4 etc..

**Comment by ForrestErickson** [comment]
Lee sent JLCPCB tiles.
Got this from JLCPCB
![image](https://github.com/PubInv/NASA-COG/assets/5836181/f97f84f1-0928-4d2b-b03e-471b56bc12a9)


Attaching the JLCPCB modified files.

[JLCPCBModified_Control_1V1_SFTtoBOM20231013_1149.xlsx](https://github.com/PubInv/NASA-COG/files/12895647/JLCPCBModified_Control_1V1_SFTtoBOM20231013_1149.xlsx)
[JLCPCBModified_Control_1v1-all-pos20231013_1159.xls](https://github.com/PubInv/NASA-COG/files/12895649/JLCPCBModified_Control_1v1-all-pos20231013_1159.xls)

**Comment by ForrestErickson** [comment]
I asked
Did you have to modify both files?
Can you describe the modification to the BOM file?
Can you describe the modification to the placement file?

Got this answer.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/8629076f-70c5-4b43-a17c-696434dbd44c)

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 
I am sufficently tired jut now, 13 Oct 12:50 PM that I can not see the difference between what I sent and what he sent back.

I sent: [Control_1V1_SFTtoBOM20231013_1149.xlsx](https://cdn.livechat-files.com/api/file/lc/att/12327960/e3d32380585a2eb8e32e2834043d4026/Control_1V1_SFTtoBOM20231013_1149.xlsx)
and
[Control_1v1-all-pos20231013_1159.xls](https://cdn.livechat-files.com/api/file/lc/att/12327960/6fe416c9c42d423afc32bc1f1bbe9921/Control_1v1-all-pos20231013_1159.xls)

**Comment by ForrestErickson** [comment]
Still getting errors trying to resolve.
Parts shortages too.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/bf8cd57e-3b1a-4858-a6f7-260705517f1c)

**Comment by ForrestErickson** [comment]
If I place an order now, Friday afternoon my time will JLCPCB be starting on it soon or will it wait till Monday your time?
avatar
Lucas 01:17 PM
you can order it now sir
we will have colleague working on tonight and tomorrow day time
to check the file and making production file
Ok thanks for the status. I will be getting approval to make the purchase soon.

TEN THOUSAND THANKS!!!

**Comment by ForrestErickson** [comment]
Change JR6 from C305981 to C2683355.

Change 4K7 from C269713 to C23162 

Change TAC switch from C13828 to C428628
Manufacturer
TE Connectivity
MFR.Part #
1825910-6
JLCPCB Part #
C428628
Package
Plugin
Description
50mA Straight SPST 160gf 24V Plugin Tactile Switches ROHS

**Comment by ForrestErickson** [comment]
Regarding, "jlcpcb doesn't like like designators like C1-C15, needs to be C1, C2, C3, C4 etc"

After some back and forth with JLCPCB it is that they want "C1-15"  They also do not want multiple spaces and commas as delimiters.
Example, from "C1,  C2,  C3,  C4 " to "C1, C2 ,C3, C4" 
They send me a video.

https://github.com/PubInv/NASA-COG/assets/5836181/3be4fe57-86bf-4e2a-a46f-a1717d9c1685

**Comment by ForrestErickson** [comment]
Order placed. 
I sent them some feedback

> Thanks you so much for the video. That makes it understandable.
> JLCPCB must be having this problem with all uses of KiCad. Am I right?
> 
> One of the methods I am using is the standard BOM generator tool from KiCad as pictured here.
> 
> The parts library system we use is now a couple of year old. I noticed that there is recently ( I do not know since when) a BOM generator script for jlcpcb.
> 
> However it is incompatible with our parts library at this time and I do not know where to read to understand a full example of such a parts library.
> Does JLCPCB have documentation on this BOM generator script?
> 
> Thanks,
> Forrest Lee Erickson
> 

Was sent the following by JLCPCB support.

> Hi there
> Thanks for your feedback.
> Seems not all users have this kind of problem﻿.
> Below guidance includes the files preparation, we hope it helps: https://jlcpcb.com/help/catalog/190-PCBA-Files-Preparation
> If you need further help please feel free to contact us. Thanks for your support.
> Best regards
> Lorraine

Closing this issue.

**Comment by ForrestErickson** [comment]
Files directly from JLCPCB.  
[Control_1v1-all-pos20231013_1633.xls](https://github.com/PubInv/NASA-COG/files/12937895/Control_1v1-all-pos20231013_1633.xls)
[JLCPCBModified_Control_1V1_SFTtoBOM20231013_1505.csv](https://github.com/PubInv/NASA-COG/files/12937896/JLCPCBModified_Control_1V1_SFTtoBOM20231013_1505.csv)


If Lee recalls directly this is the exact file with which the order of 20231016.

**Comment by ForrestErickson** [comment]
Made new files
[ReOrder_Control_1V1_SFTtoBOM20231017_1431.csv](https://github.com/PubInv/NASA-COG/files/12998645/ReOrder_Control_1V1_SFTtoBOM20231017_1431.csv)
[ReOrder_Control_1V1_SFTtoBOM20231017_Control_1v1-top-pos.csv](https://github.com/PubInv/NASA-COG/files/12998646/ReOrder_Control_1V1_SFTtoBOM20231017_Control_1v1-top-pos.csv)


Submitted 20231018. Again got error.
"The BOM file doesn't match the CPL file, please check and re-upload the files."

Pressed "continue" anyway.
Now there are part shortages
![image](https://github.com/PubInv/NASA-COG/assets/5836181/7e9def80-2212-4248-89d0-5606283b0359)

C168673, 
C269434,
C269701

I found substitutes. 
For the C168673 part it looks like I can use C3012204 which is in stock. I will try to make the substitution selection now.
For the 1R0, I have selected C140111
And for the 10K I have selected C25804

I placed order.

![image](https://github.com/PubInv/NASA-COG/assets/5836181/62496012-a9d6-4c72-8f0c-5484af205e16)

**Comment by ForrestErickson** [comment]
Received confirmation email.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/043e054e-fc2c-46f2-8248-dac9680460a4)
