### ISSUE TITLE
If the Due is started up before the power supplies are plugged in, the heater comes on in appropriately....

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#43]
and seems to stay on.

**Comment by LokiMetaSmith** [comment]
An external pull down resistor should be applied to the circuit.

**Comment by ForrestErickson** [comment]
@RobertLRead
Has the system evolved so that this is no longer a problem and the solution is implemented in Serial number 1 and Serial number 2
Can this issue can be changed to Done and closed?

**Comment by LokiMetaSmith** [comment]
This issue needs updating from @RobertLRead as it affects the build up of ODECS no. 2 and the heater controller

**Comment by LokiMetaSmith** [comment]
This hasn't been observed in the Stage2 heater, which has a power breaker for enabling and disabling the DUE controller. 

The difference may be the different SSR manufacturers.
