### ISSUE TITLE
Pins D52,D53 seems not to be pulled low, and although code not written yet...

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#44]
to control these, this is turning on one of the planned 110VAC channels at startup time. They should both clearly intialize to off.

**Comment by ForrestErickson** [comment]
@RobertLRead 
Has the system evolved so that this is no longer a problem and the solution is implemented in Serial number 1 and Serial number 2 
Can this issue can be changed to Done and closed?

**Comment by LokiMetaSmith** [comment]
The fan controllers had the same issue, although this hasn't been observed in the most recent version of Stage 2 heater or OEDCS#2 I'm going to assume it's been changed. 

closing for now
