### ISSUE TITLE
Add an important configuration of machine specific parameters 4 HR

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#5]
The NASA-COG problem has many important internal parameters, such as the target warmup temperature, the maximum stack voltage, the maximum rate of stack voltage change, etc. These should be added to the task property to allow these values to be set and (in serial_task) and acted upon in (cog_task).

**Comment by ForrestErickson** [comment]
@RobertLRead ,
Status?
Can this be closed or marked Will Not Fix?
