### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#55]
all images are not in the repository, so the 2D sample images of individual components don't show up. Also need a relative image address location. 

C:/Users/Lawrence/AppData/Local/Temp/FreeCAD_Doc_281452ef-23f5-43b0-8110-d7c71acc7f8f_ea4a6e_13672/GFIReceptical.png

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 

I believe I have committed and pushed all the necessary images.
Please check and confirm.

Thanks,
Lee

**Comment by ForrestErickson** [comment]
@LokiMetaSmith 

Please check and confirm.

Thanks,
Lee

**Comment by RobertLRead** [comment]
@LokiMetaSmith this is old, I suspect you can close it.
