### ISSUE TITLE
Need to Check PWM frequency of the Due....

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#69]
The standard seems to be 25 KHz. I don't know if we are close to that.

**Comment by ForrestErickson** [comment]
Lee has read several articles about the PWM frequency for control of PC fans like the FOXCOMM 92mm and the GDSTIME GDP1238 120mm fan he has. Of the several articles read, the articles have NEVER found a difference controlling the PC fans at the Arduino PWM frequency of 430 or 960 verses 25 KHz. 

The 24Volt fan which in May 2023 has become of interest may be different.
