### ISSUE TITLE
Test and understand the Tachometer Feature of the 24V blower with both code and an oscilloscope

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#75]
The blower that AmOx specified provides a tachometer.  However, the tachometer does not read if power is shut off due to pulsed of PWM control, making it a bit complicated. This issue is run the fan at a steady voltage at fulll power (24V) and at lower voltages (8V seems to lowest reliable voltage that causes turning) and make sure we can read the tach reliably at all of those voltages.

**Comment by ForrestErickson** [comment]
## Lee's Notes on a 12V Fan, Foxconn

I reduced the supply voltage from 12 V slowly until the fan stopped rotating. The FG (Tachometer) signal was producing counts till the fan stopped rotating at about 3.15 Volts.
Screen shot. Chanel 2 is the FG signal and is high., Channel 4 is the supply into the fan 
![image](https://github.com/PubInv/NASA-COG/assets/5836181/64dae190-1a47-45f4-9e86-064f95eff631)

I could blow on the fan blade and cause rotation which the FG signal registered.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/f1aadc68-9443-477d-8ff2-3e5e25daf9ec)
However the FG signal is not the full amplitude.  The waveform high was 5 volts but the low was on the order of 3.5 volts. 

From a stalled state, Lee increased the voltage to the fan and at about 4.9 the fan started and the FG signals is a signal with low of about 1.4 volt and a high of about 5 volts.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/ac3fd6bd-b080-47c7-b234-ea83c316dbd9)

Note the vertical scale on channel 2 has been changed on this image.

**Comment by ForrestErickson** [comment]
## 12V Fan, Foxconn, Experimenting with low supply voltage and FG counting with Arduino UNO.

Lee reduced the voltage till the fan stalled and confirmed the FG count on the UNO serial port went to zero.

Lee increased the voltage on the fan but not enough to start or sustain rotation.  Lee could blow on the fan blades to start rotation and the UNO counted.
Here are waveforms as the fan spun down and stopped.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/255a4bac-f7b6-493c-ba8f-7a6cb5a7aa8d)

Here is the UNO serial port screen capture of the fan slowing down and the counting stopping.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/40a433ff-dac9-4af3-a1f1-ad5284b6e537)

HOWEVER, There is a regime where the FG signal is toggling but the UNO is NOT counting and reports frequency is zero.  With low voltage supply to the fan counting of the FG becomes unreliable and reports zero when the fan has slow rotation.

**Comment by ForrestErickson** [comment]
## 12V Fan, Foxconn, Power Turn Off Test for FG

With the Foxconn fan running at 12 V Lee turned off the power and captured the decay of the supply voltage and the FG signal.  

![image](https://github.com/PubInv/NASA-COG/assets/5836181/9252c379-0256-4a49-8656-5ed5a87e3a95)


At about 6.75 divisions from the left the FG stopped thought visual the fan was still spinning.  The Supply voltage was about 2.6 Volts per the cursor.

Therefor at low supply voltages the FG signal (Tachometer) stops.

When the supply has decayed to a bit below 7.2 the FG signal (Tachometer) is no longer making a normal low signal
![image](https://github.com/PubInv/NASA-COG/assets/5836181/b4baf9e2-66e3-4f7d-ac23-b98548ac39b7)

**Comment by LokiMetaSmith** [comment]
I believe this is complete. 

While the TACH is useful for verifying the fan is moving, it cannot be used to determine a "blocked fan". However, a "blocked fan" event can be determined indirectly from the step response of fan speed, heater and oxygen stack power on the total thermal heat flux of the system.

**Comment by ForrestErickson** [comment]
Specification showing internal circuitry for blower
https://docs.rs-online.com/1c09/0900766b816e68bb.pdf

Example of common connections:
![image](https://github.com/PubInv/NASA-COG/assets/5836181/39d0db10-97cc-44ff-872f-b0fea9350175)
