### ISSUE TITLE
Is Redundant, Dual Source, AC Power Connections a Requirement?

### ISSUE THREAD

**Issue by ForrestErickson** [PubInv/NASA-COG#77]
In an installed system will their be two or more AC mains sources (back up generators for example)
Where will the switch over take place?

In computer server systems hot swappable power supplies plug into out let strips identified for the different AC Lines such as A line and B line.

**Comment by LokiMetaSmith** [comment]
Switching takes place at the breaker for the building, it is not a requirement that the device has dual source power requirements. 
The current projection is that multiple COG units will be in parallel and so failure in one unit only decreases production capacity.
