### ISSUE TITLE
Just an Idea: Could we use the Google Sheets API to hold the parameters?

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/NASA-COG#82]
https://developers.google.com/sheets/api/samples/reading#:~:text=The%20Google%20Sheets%20API%20allows,of%20ranges%2C%20and%20entire%20sheets.

Dear Geoff,

I wonder if we could have the MGOGServer read a Google Sheets document rather than a file? This might be a way for us to solve the problem of logging into the server and making a file.  We should probably wait until we have confirmation from the user American Oxygen that they would like this, but it is a nifty thought.

**Comment by LokiMetaSmith** [comment]
You would need to define the ramp procedure as an entire fixed step number of element cells. 
Since it's a a simple GET request, the API should be trivial to implement as the return value is JSON and so should already have a parser in the firmware for our existing system.
